# Generated by Django 4.1.4 on 2022-12-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='')),
                ('author', models.CharField(max_length=120, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
            ],
        ),
    ]
