# Generated by Django 4.1.4 on 2022-12-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120, verbose_name='العنوان'),
        ),
    ]
